### ISSUE TITLE
Error 400 on create-activity

### ISSUE THREAD

**Issue by simonmoreau** [petrbroz/forge-cli-utils#5]
In the `setup-pipeline.ps1`, when running `forge-da create-activity`, the console send the following result:

```
Creating/updating an activity
Request failed with status code 400
```

After some research, it seems to be linked to the following error

```
{
    "commandLine": [
        "Invalid switch [$(args[rvtFile].path)]. Variables that expand to paths must be quoted. (Parameter 'commandLine')"
    ]
}
```

**Comment by petrbroz** [comment]
Addressed by https://github.com/petrbroz/forge-cli-utils/pull/6.
